/* ZY-L1-7620N */

#define BOARD_PID		"ZY-L1-7620N"
#define BOARD_NAME		"ZY-L1-7620N"
#define BOARD_DESC		"ZY-L1-7620N Wireless Router"
#define BOARD_VENDOR_NAME	"CMCC"
#define BOARD_VENDOR_URL	"http://www.techmes.cn"
#define BOARD_MODEL_URL		"http://www.techmes.cn"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120
#undef  BOARD_GPIO_BTN_RESET
#define BOARD_GPIO_BTN_WPS	1
#undef  BOARD_GPIO_LED_ALL
#define BOARD_GPIO_LED_WIFI	72
#define BOARD_GPIO_LED_POWER	38
#undef BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_WAN
#define BOARD_GPIO_LED_USB	39
#undef BOARD_GPIO_LED_ROUTER
#undef BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
